apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service
        image: 809567559836.dkr.ecr.us-west-2.amazonaws.com/devops-project:product-service1
        ports:
        - containerPort: 8080