apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: localhost:5000/product-service:latest
          ports:
            - containerPort: 8080
          # env:
          #   - name: MONGO_HOST
          #     value: mongo-service
          #   - name: MONGO_PORT
          #     value: "27017"
